export const USERS = [
  {
    id: 1,
    firstName: "Sarge",
    lastName: "Georgeon",
    email: "sgeorgeon0@ibm.com",
    gender: "Male",
    avatar: "https://robohash.org/evenietquisaepe.png?size=50x50&set=set1",
  },
  {
    id: 2,
    firstName: "Valma",
    lastName: "Patrickson",
    email: "vpatrickson1@epa.gov",
    gender: "Female",
    avatar: "https://robohash.org/maximeofficiaet.png?size=50x50&set=set1",
  },
  {
    id: 3,
    firstName: "Riane",
    lastName: "Pollicote",
    email: "rpollicote2@senate.gov",
    gender: "Agender",
    avatar: "https://robohash.org/solutanullalibero.png?size=50x50&set=set1",
  },
  {
    id: 4,
    firstName: "Lavena",
    lastName: "Barratt",
    email: "lbarratt3@discovery.com",
    gender: "Female",
    avatar: "https://robohash.org/ettotamet.png?size=50x50&set=set1",
  },
  {
    id: 5,
    firstName: "Esmeralda",
    lastName: "Calvard",
    email: "ecalvard4@ocn.ne.jp",
    gender: "Female",
    avatar: "https://robohash.org/minimautporro.png?size=50x50&set=set1",
  },
  {
    id: 6,
    firstName: "Olly",
    lastName: "Leavy",
    email: "oleavy5@prnewswire.com",
    gender: "Female",
    avatar: "https://robohash.org/voluptasomnisfugit.png?size=50x50&set=set1",
  },
  {
    id: 7,
    firstName: "Melly",
    lastName: "Kinnen",
    email: "mkinnen6@tmall.com",
    gender: "Female",
    avatar: "https://robohash.org/solutaautet.png?size=50x50&set=set1",
  },
  {
    id: 8,
    firstName: "Ancell",
    lastName: "Dunning",
    email: "adunning7@e-recht24.de",
    gender: "Male",
    avatar: "https://robohash.org/consequaturrationeet.png?size=50x50&set=set1",
  },
  {
    id: 9,
    firstName: "Hebert",
    lastName: "Fairholm",
    email: "hfairholm8@businesswire.com",
    gender: "Male",
    avatar:
      "https://robohash.org/molestiaeomnismolestias.png?size=50x50&set=set1",
  },
  {
    id: 10,
    firstName: "Ellsworth",
    lastName: "Ibbitson",
    email: "eibbitson9@vimeo.com",
    gender: "Male",
    avatar: "https://robohash.org/ducimuscorruptiautem.png?size=50x50&set=set1",
  },
];